/home/kaloyants/Documents/spo/build/mandelbrot -t 1 -g 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 1 -g 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 1 -g 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 1 -g 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 1 -g 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 1 -g 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 1 -g 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 1 -g 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 1 -g 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 1 -g 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 1 -g 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 1 -g 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 1 -g 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 1 -g 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 1 -g 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 1 -g 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 2 -g 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 2 -g 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 2 -g 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 2 -g 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 2 -g 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 2 -g 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 2 -g 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 2 -g 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 2 -g 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 2 -g 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 2 -g 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 2 -g 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 2 -g 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 2 -g 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 2 -g 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 2 -g 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 4 -g 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 4 -g 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 4 -g 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 4 -g 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 4 -g 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 4 -g 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 4 -g 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 4 -g 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 4 -g 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 4 -g 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 4 -g 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 4 -g 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 4 -g 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 4 -g 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 4 -g 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 4 -g 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 8 -g 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 8 -g 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 8 -g 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 8 -g 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 8 -g 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 8 -g 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 8 -g 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 8 -g 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 8 -g 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 8 -g 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 8 -g 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 8 -g 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 8 -g 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 8 -g 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 8 -g 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 8 -g 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 16 -g 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 16 -g 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 16 -g 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 16 -g 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 16 -g 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 16 -g 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 16 -g 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 16 -g 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 16 -g 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 16 -g 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 16 -g 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 16 -g 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 16 -g 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 16 -g 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 16 -g 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 16 -g 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 32 -g 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 32 -g 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 32 -g 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 32 -g 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 32 -g 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 32 -g 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 32 -g 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 32 -g 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 32 -g 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 32 -g 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 32 -g 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 32 -g 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 32 -g 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 32 -g 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 32 -g 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 32 -g 8