/home/kaloyants/Documents/spo/build/mandelbrot -t 1 -g 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 1 -g 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 1 -g 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 1 -g 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 2 -g 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 2 -g 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 2 -g 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 2 -g 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 4 -g 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 4 -g 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 4 -g 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 4 -g 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 8 -g 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 8 -g 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 8 -g 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 8 -g 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 16 -g 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 16 -g 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 16 -g 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 16 -g 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 32 -g 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 32 -g 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 32 -g 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 32 -g 16