/home/kaloyants/Documents/spo/build/mandelbrot -t 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 1
/home/kaloyants/Documents/spo/build/mandelbrot -t 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 2
/home/kaloyants/Documents/spo/build/mandelbrot -t 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 4
/home/kaloyants/Documents/spo/build/mandelbrot -t 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 8
/home/kaloyants/Documents/spo/build/mandelbrot -t 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 16
/home/kaloyants/Documents/spo/build/mandelbrot -t 32
/home/kaloyants/Documents/spo/build/mandelbrot -t 32
/home/kaloyants/Documents/spo/build/mandelbrot -t 32
/home/kaloyants/Documents/spo/build/mandelbrot -t 32